MKLINT:=no
MKPROFILE:=no
MKPIC:=no

SRCROOT=	../..
.include "$(SRCROOT)/pttbbs.mk"

SRCS:=	file.c lock.c log.c net.c sort.c string.c time.c crypt.c record.c osdep.c
LIB:=	cmsys

install:

.include <bsd.lib.mk>
