# $Id$

##########
# use googletest as test-framework
##########

TESTROOT:=	../..

SRCROOT:= ../../..
.include "$(SRCROOT)/pttbbs.mk"
.include "$(SRCROOT)/pttbbs_cond.mk"

##########
# test
##########

TEST_PROGS=	test_dummy test_util_db test_pttdb_util test_pttdb_uuid test_pttdb_dict_bson_by_uu test_pttdb_main test_pttdb_content_block test_pttdb_comment test_pttdb_comment_reply test_pttdb_file_info

#######################################################################
# test
#######################################################################

.include "$(SRCROOT)/pttbbs_test.mk"
