# $Id$

##########
# use googletest as test-framework
##########

TESTROOT:=	../..

SRCROOT:= ../../..
.include "$(SRCROOT)/pttbbs.mk"
.include "$(SRCROOT)/pttbbs_cond.mk"

##########
# test
##########

TEST_PROGS=	test_dummy test_migrate_pttdb_to_file test_migrate_file_to_pttdb

#######################################################################
# test
#######################################################################

.include "$(SRCROOT)/pttbbs_test.mk"
