/* $Id$ */
#ifndef PTTDB_CONST_H
#define PTTDB_CONST_H

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_BUF_SIZE 8192
#define MAX_CREATE_MILLI_TIMESTAMP 9999999999999 // XXX 2286-11-20

#define MIN_CREATE_TIMESTAMP 810000000

#define MIN_CREATE_MILLI_TIMESTAMP MIN_CREATE_TIMESTAMP * 1000

enum LiveStatus {
    LIVE_STATUS_ALIVE,
    LIVE_STATUS_DELETED,
};

enum PttDBStorageType {
    PTTDB_STORAGE_TYPE_MONGO,
    PTTDB_STORAGE_TYPE_FILE,
    PTTDB_STORAGE_TYPE_OTHER,
    N_PTTDB_STORAGE_TYPE,
};

enum PttDBContentType {
    PTTDB_CONTENT_TYPE_MAIN,
    PTTDB_CONTENT_TYPE_COMMENT,
    PTTDB_CONTENT_TYPE_COMMENT_REPLY,
    PTTDB_CONTENT_TYPE_OTHER,
    N_PTTDB_CONTENT_TYPE,
};

#ifdef __cplusplus
}
#endif

#endif /* PTTDB_CONST_H */
