# $Id$

##########
# use googletest as test-framework
##########

TESTROOT:=	../..

SRCROOT:= ../../..
.include "$(SRCROOT)/pttbbs.mk"
.include "$(SRCROOT)/pttbbs_cond.mk"

##########
# test
##########

TEST_PROGS=	test_dummy test_pttui_thread_lock test_pttui_thread test_pttui_buffer test_pttui_resource_info test_pttui_resource_dict

#######################################################################
# test
#######################################################################

.include "$(SRCROOT)/pttbbs_test.mk"
