# $Id$

##########
# use googletest as test-framework
##########

TESTROOT:=      ../..

SRCROOT:=		../../..

.include "$(SRCROOT)/pttbbs.mk"
.include "$(SRCROOT)/pttbbs_cond.mk"

##########
# test
##########

TEST_PROGS=	test_pttui_thread_lock test_pttui_thread

.include "$(SRCROOT)/pttbbs_test.mk"
