# $Id$

##########
# use googletest as test-framework
##########

TESTROOT:=	../..

SRCROOT:= ../../..
.include "$(SRCROOT)/pttbbs.mk"
.include "$(SRCROOT)/pttbbs_cond.mk"

##########
# test
##########

TEST_PROGS=	test_dummy test_ptt_link_list test_ptt_queue

#######################################################################
# test
#######################################################################

.include "$(SRCROOT)/pttbbs_test.mk"
